Task 1

In [ ]:
import numpy as np
# Define two matrices
A = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
B = np . array ([[7 , 8] , [9 , 10] , [11 , 12]])
# Matrix multiplication using np.dot
result_dot = np . dot (A , B )
print (" Result with np.dot :\n", result_dot )

 Result with np.dot :
 [[ 58  64]
 [139 154]]


Task 2

In [ ]:
import numpy as np

# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])

# Slicing examples
print("Basic:",
      "arr1d:", arr1d[1:4],
      "arr2d:", arr2d[1:3, 0:2],
      "arr3d:", arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d: [1 2 3] arr2d: [[3 4] [6 7]] arr3d: [[[5] [7]]]

print("Step:",
      "arr1d:", arr1d[1:5:2],
      "arr2d:", arr2d[::2, 1::2],
      "arr3d:", arr3d[::2, ::2, 1::2])
# Output Step: arr1d: [1 3] arr2d: [[1] [7]] arr3d: [[[1] [9]]]



Basic: arr1d: [1 2 3] arr2d: [[3 4]
 [6 7]] arr3d: [[[5]
  [7]]]
Step: arr1d: [1 3] arr2d: [[1]
 [7]] arr3d: [[[1]]

 [[9]]]


Task 3

In [ ]:
import numpy as np
# Define two matrices
A = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
B = np . array ([[7 , 8] , [9 , 10] , [11 , 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print (" Result with @ operator :\n", result_at )

# Matrix multiplication using np. matmul
result_matmul = np . matmul (A , B )
print (" Result with np. matmul :\n", result_matmul )

 Result with @ operator :
 [[ 58  64]
 [139 154]]
 Result with np. matmul :
 [[ 58  64]
 [139 154]]


Task 4

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
print("2-Norm (Euclidean):", np.linalg.norm(A))
print("Solution x:", np.linalg.solve(A, B))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


Task 5

In [ ]:
import numpy as np
import random
from timeit import timeit

# Define a function to add two lists using pure Python
def add_python(Z1, Z2):
    # Element-wise addition using list comprehension
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

# Define a function to add two arrays using NumPy
def add_numpy(Z1, Z2):
    # Element-wise addition using NumPy
    return np.add(Z1, Z2)

# Generate large random data for testing
size = 100000  # Size of the sample data (large to observe performance difference)

# Create two random lists with 'size' elements
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)

# Convert the lists to NumPy arrays
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)

# Measure the execution time for the pure Python addition
python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(), number=100)

# Measure the execution time for the NumPy addition
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print the execution times for comparison
print(f"Pure Python addition: {python_time:.6f} seconds per loop")
print(f"NumPy addition: {numpy_time:.6f} seconds per loop")

Pure Python addition: 2.170921 seconds per loop
NumPy addition: 0.011109 seconds per loop


Task 6

In [ ]:
import numpy as np

# Initialize an all-zero array with size 2 x 3:
zeros_arr = np.zeros((2, 3))
print("A zeros array is:\n", zeros_arr, "\nwith dimensions:", zeros_arr.shape, "\n")

A zeros array is:
 [[0. 0. 0.]
 [0. 0. 0.]] 
with dimensions: (2, 3) 



Task 7

In [ ]:
import numpy as np

# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



Task 8

In [ ]:
import numpy as np

# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



Task 9

In [ ]:
import numpy as np

# Create an array with shape (2, 3)
array = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)

# Print original and reshaped shapes
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


Task 10

In [ ]:
import numpy as np

# Example 1: Using numpy arange
a = np.arange(1, 10)
print(a)

# Example 2: Using Python's range
x = range(1, 10)
print(x)  # x is an iterator
print(list(x))  # Convert the range object to a list and print

# Further numpy arange examples:
x = np.arange(10.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


Task 11

In [ ]:
import numpy as np

# 50 values between 1 and 10:
print(np.linspace(1, 10))

# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))

# Excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


Task 12

In [ ]:
import numpy as np

# Create arrays of specified shapes
ones_array = np.ones((2, 3))  # Shape: (2, 3)
zeros_array = np.zeros((3, 2))  # Shape: (3, 2)
empty_array = np.empty((2, 2))  # Shape: (2, 2)
identity_matrix = np.eye(3)  # Shape: (3, 3)

# Print the arrays
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[2.  1. ]
 [1.5 0.5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 13

In [ ]:
import numpy as np

# Create arrays from list, tuple, and nested list
array_from_list = np.array([1, 2, 3])  # [1 2 3]
array_from_tuple = np.array((4, 5, 6))  # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]])  # [[1 2 3] [4 5 6]]

# Print the arrays
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


Task 14

In [ ]:
import numpy as np

# Existing Array of Shape: (2, 3)
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Creating Arrays with the Shape of the existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape)  # Shape: (2, 3)

# Print the arrays
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.71320251e-310 0.00000000e+000 6.66471434e-310]
 [6.66469324e-310 6.66469324e-310 6.66469331e-310]]


Task 15

In [ ]:
import numpy as np

# Original array
array = np.array([1, 2, 3])

# Multiplies each element by 2, result: [2, 4, 6]
new_array = array * 2

# Creates a new array with the same elements
copied_array = np.copy(array)

# Slices elements from index 1 to 3, result: [2, 3]
sliced_array = array[1:3]

# Print the arrays
print("Original array:", array)
print("New array (multiplied by 2):", new_array)
print("Copied array:", copied_array)
print("Sliced array (index 1 to 3):", sliced_array)

Original array: [1 2 3]
New array (multiplied by 2): [2 4 6]
Copied array: [1 2 3]
Sliced array (index 1 to 3): [2 3]


Task 16

In [ ]:
import numpy as np

# Arrays to stack
arr1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]])  # Shape: (2, 2)

# Stacking examples

# Horizontal stacking: arr1 and arr2 side by side
hstacked = np.hstack((arr1, arr2))
# Output: [[1 2 5 6] [3 4 7 8]]

# Vertical stacking: arr1 and arr2 on top of each other
vstacked = np.vstack((arr1, arr2))
# Output: [[1 2] [3 4] [5 6] [7 8]]

# Column stacking: arr1[0] and arr2[0] stacked as columns
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output: [[1 5] [2 6]]

# Print the arrays
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


Task 17

In [ ]:
import numpy as np

# Arrays to concatenate
arr1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]])  # Shape: (2, 2)

# Concatenate along axis 0 (vertical)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape: (4, 2)

# Concatenate along axis 1 (horizontal)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape: (2, 4)

# Print the concatenated arrays
print(concat_axis0, concat_axis1, sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]




**Worksheet 1 **

Problem 1. Array Creation

In [ ]:
import numpy as np

# Initialize an empty array of size 2X2
empty_array = np.empty((2, 2))
print("Empty Array of 2X2:\n", empty_array)

# Initialize an all-ones array of size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array of (4X2):\n", ones_array)

#Initialize a size 2x2 array of fill value
fill_value = 8
filled_array = np.full((2, 2), fill_value)
print("\nArray filled with value 8 (2x2):\n", filled_array)

given_array = np.array([[1, 2,], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array with same shape as given array:\n", zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\nOnes Array with same shape as given array:\n", ones_like_array)

#Converting list into array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty Array of 2X2:
 [[4.99288307e-310 0.00000000e+000]
 [6.81794736e-310 6.81794742e-310]]

All Ones Array of (4X2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 8 (2x2):
 [[8 8]
 [8 8]]

Zeros Array with same shape as given array:
 [[0 0]
 [0 0]]

Ones Array with same shape as given array:
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem 2. Array Manipulation

In [ ]:
import numpy as np

#Initialize an array with value ranging from 10 to 49
array_range= np.arange(10, 50)
print("Array Range from 10 to 40:\n", array_range)

#Initialize a 3x3 matrix value from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

#Initialize a 3x3 identity matrix
identity_matrix=np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of the array:", mean_value)


Array Range from 10 to 40:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.33066108 0.2289249  0.56169212 0.71703612 0.93980612 0.10876759
 0.93074823 0.98238904 0.84839744 0.22861254 0.27557166 0.55535808
 0.95747638 0.17686812 0.12293734 0.1190608  0.70865725 0.30297262
 0.2719397  0.75929146 0.17969429 0.58917931 0.89873485 0.24187542
 0.26437467 0.09671026 0.57354846 0.74205357 0.71023048 0.81046336]
Mean of the array: 0.5078011091809619


Problem 3. Array Operations

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Adding two arrays (x and y)
array_addition = x + y
print("1. Addition of x and y:")
print(array_addition)

# Subtracting two arrays (x and y)
array_subtraction = x - y
print("\n2. Subtraction of x and y:")
print(array_subtraction)

# Multiplying the array v by an integer
array_multiplication = v * 2
print("\n3. Multiplication of v by 3:")
print(array_multiplication)

# Finding the square of each element in the array w
array_square = np.square(w)
print("\n4. Square of each element in array w:")
print(array_square)
# Finding the dot product between:
dot_v_w = np.dot(v, w)
print(f"Dot product of v and w: {dot_v_w}")

dot_x_v = np.dot(x, v)
print(f"Dot product of x and v: {dot_x_v}")

dot_x_y = np.dot(x, y)
print(f"Dot product of x and y:\n{dot_x_y}")



# Concatenate x and y along rows, and concatenate v and w along columns
concat_x_y = np.concatenate((x, y), axis=0)  # Row-wise concatenation
concat_v_w = np.vstack((v, w))  # Column-wise concatenation
print("Concatenate x and y along rows:")
print(concat_x_y)
print("Concatenate v and w along columns:")
print(concat_v_w)

# Concatenate x and v; explain the error if any
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x and v along rows:")
    print(concat_x_v)
except ValueError as e:
    print("\n7. Error when concatenating x and v along rows:")
    print(e)

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of v by 3:
[18 20]

4. Square of each element in array w:
[121 144]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]
Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

7. Error when concatenating x and v along rows:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4. Matrix Operation

In [ ]:
import numpy as np

# Define the matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove that A * A^(-1) = I (Identity Matrix)
A_inv = np.linalg.inv(A)  # Calculate the inverse of A
identity_matrix = np.dot(A, A_inv)  # Multiply A with its inverse
print("1. Prove A * A^(-1) = I:")
print(identity_matrix)

# 2. Prove that AB ≠ BA
AB = np.dot(A, B)  # Multiply A and B
BA = np.dot(B, A)  # Multiply B and A
print("\n2. Prove AB ≠ BA:")
print("AB =")
print(AB)
print("BA =")
print(BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)  # Transpose of AB
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)  # B^T * A^T
print("\n3. Prove (AB)^T = B^T * A^T:")
print("(AB)^T =")
print(AB_transpose)
print("B^T * A^T =")
print(BT_AT)
print("Are (AB)^T and B^T * A^T equal? ", np.array_equal(AB_transpose, BT_AT))



1. Prove A * A^(-1) = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB ≠ BA:
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
Are AB and BA equal?  False

3. Prove (AB)^T = B^T * A^T:
(AB)^T =
[[23 51]
 [13 29]]
B^T * A^T =
[[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal?  True


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficients matrix
B = np.array([-1, -3, 9])  # Constants matrix

# Solve for X using the inverse method
A_inv = np.linalg.inv(A)  # Inverse of A
X = np.dot(A_inv, B)
print("\nSolution to the system of equations using the inverse method:")
print("X (values of x, y, z) =")
print(X)



Solution to the system of equations using the inverse method:
X (values of x, y, z) =
[ 2.  1. -2.]


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Element-wise Addition
def element_wise_addition():
    size = 1_000_000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python Lists
    start_time = time.time()
    list_result = [list1[i] + list2[i] for i in range(size)]
    list_time = time.time() - start_time
    print(f"Element-wise Addition with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    array_result = array1 + array2
    numpy_time = time.time() - start_time
    print(f"Element-wise Addition with NumPy Arrays: {numpy_time:.4f} seconds")
    # Element-wise Multiplication
def element_wise_multiplication():
    size = 1_000_000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python Lists
    start_time = time.time()
    list_result = [list1[i] * list2[i] for i in range(size)]
    list_time = time.time() - start_time
    print(f"Element-wise Multiplication with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    array_result = array1 * array2
    numpy_time = time.time() - start_time
    print(f"Element-wise Multiplication with NumPy Arrays: {numpy_time:.4f} seconds")

# Dot Product
def dot_product():
    size = 1_000_000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python Lists
    start_time = time.time()
    dot_product = sum(list1[i] * list2[i] for i in range(size))
    list_time = time.time() - start_time
    print(f"Dot Product with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    dot_product = np.dot(array1, array2)
    numpy_time = time.time() - start_time
    print(f"Dot Product with NumPy Arrays: {numpy_time:.4f} seconds")

# Matrix Multiplication
def matrix_multiplication():
    size = 1000
    matrix1 = [[i for i in range(size)] for _ in range(size)]
    matrix2 = [[i for i in range(size)] for _ in range(size)]
    np_matrix1 = np.array(matrix1)
    np_matrix2 = np.array(matrix2)
    # Using Python Lists
    start_time = time.time()
    result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
    list_time = time.time() - start_time
    print(f"Matrix Multiplication with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    result = np.dot(np_matrix1, np_matrix2)
    numpy_time = time.time() - start_time
    print(f"Matrix Multiplication with NumPy Arrays: {numpy_time:.4f} seconds")

# Run the experiments
element_wise_addition()
element_wise_multiplication()
dot_product()
matrix_multiplication()

Element-wise Addition with Python Lists: 0.1359 seconds
Element-wise Addition with NumPy Arrays: 0.0046 seconds
Element-wise Multiplication with Python Lists: 0.1318 seconds
Element-wise Multiplication with NumPy Arrays: 0.0050 seconds
Dot Product with Python Lists: 0.2620 seconds
Dot Product with NumPy Arrays: 0.0019 seconds
Matrix Multiplication with Python Lists: 246.0360 seconds
Matrix Multiplication with NumPy Arrays: 1.3085 seconds
